### ISSUE TITLE
Soca push Error

### ISSUE THREAD

**Issue by samuelandert** [quirkey/action#3]
Soca push is giving me the following error.
Any idea?

/Library/Ruby/Gems/1.8/gems/soca-0.3.2/lib/soca/pusher.rb:121:in `run_hook_file!': undefined method`plugin' for #Soca::Pusher:0x105b92840 (NoMethodError)
    from /Library/Ruby/Gems/1.8/gems/soca-0.3.2/lib/soca/pusher.rb:120:in `chdir'
    from /Library/Ruby/Gems/1.8/gems/soca-0.3.2/lib/soca/pusher.rb:120:in`run_hook_file!'
    from /Library/Ruby/Gems/1.8/gems/soca-0.3.2/lib/soca/pusher.rb:112:in `run_hooks!'
    from /Library/Ruby/Gems/1.8/gems/soca-0.3.2/lib/soca/pusher.rb:34:in`build'
    from /Library/Ruby/Gems/1.8/gems/soca-0.3.2/lib/soca/pusher.rb:84:in `push!'
    from /Library/Ruby/Gems/1.8/gems/soca-0.3.2/lib/soca/cli.rb:111:in`push'
    from /Library/Ruby/Gems/1.8/gems/thor-0.14.6/lib/thor/task.rb:22:in `send'
    from /Library/Ruby/Gems/1.8/gems/thor-0.14.6/lib/thor/task.rb:22:in`run'
    from /Library/Ruby/Gems/1.8/gems/thor-0.14.6/lib/thor/invocation.rb:118:in `invoke_task'
    from /Library/Ruby/Gems/1.8/gems/thor-0.14.6/lib/thor.rb:263:in`dispatch'
    from /Library/Ruby/Gems/1.8/gems/thor-0.14.6/lib/thor/base.rb:389:in `start'
    from /Library/Ruby/Gems/1.8/gems/soca-0.3.2/bin/soca:5
    from /usr/bin/soca:19:in`load'
    from /usr/bin/soca:19

**Comment by quirkey** [comment]
If you're using a Soca app generated before 0.3.2 - you need to update your hook files. Plugins are now included in the config.json file.
